import { useEffect, useRef, useState } from "react";
import { ExternalLink, MapPin, MoreHorizontal, X } from "lucide-react";
import { hasSupabaseConfig, listRecords, subscribeToTable } from "../lib/data";

export default function TrackerView() {
  const [trackers, setTrackers] = useState([]); const [bikes, setBikes] = useState([]); const [status, setStatus] = useState(""); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(""); const host = useRef(null); const map = useRef(null); const marker = useRef(null);
  const load = async () => { if (!hasSupabaseConfig) return setMessage("Connect Supabase to view live tracker data."); const [trackersResult, bikesResult] = await Promise.all([listRecords("trackers", { pageSize: 500 }), listRecords("bikes", { pageSize: 500 })]); const error = trackersResult.error || bikesResult.error; if (error) return setMessage(error.message); setTrackers(trackersResult.data); setBikes(bikesResult.data); setMessage(""); };
  useEffect(() => { load(); const off = subscribeToTable("trackers", load); return off; }, []);
  const rows = trackers.filter(t => !status || status === (t.is_online ? "online" : "offline"));
  useEffect(() => { if (!selected || !host.current || !window.L || selected.latitude == null || selected.longitude == null) return; const point = [Number(selected.latitude), Number(selected.longitude)]; if (!map.current) { map.current = window.L.map(host.current).setView(point, 16); window.L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 19, attribution: "© OpenStreetMap contributors" }).addTo(map.current); } map.current.setView(point, 16); marker.current?.remove(); marker.current = window.L.circleMarker(point, { radius: 13, color: "#d92d20", fillColor: "#f04438", weight: 3, fillOpacity: 1 }).addTo(map.current).bindTooltip(`LIVE · ${selected.identifier}`, { permanent: true, direction: "top", className: "live-location-label" }); setTimeout(() => map.current?.invalidateSize(), 0); }, [selected]);
  useEffect(() => () => { map.current?.remove(); map.current = null; }, []);
  const product = selected && bikes.find(b => b.id === selected.bike_id);
  return <><section className="panel module-table"><div className="panel-heading"><div><h2>GPS Trackers</h2><p>Click a device to open its latest live location.</p></div></div><div className="directory-filters"><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All tracker status</option><option value="online">Online</option><option value="offline">Offline</option></select></div>{message && <div className="import-message">{message}</div>}<div className="table-wrap"><table><thead><tr><th>Tracker</th><th>Product</th><th>Last seen</th><th>Status</th><th/></tr></thead><tbody>{rows.map(t => <tr key={t.id} className="tracker-row" onClick={() => setSelected(t)}><td><strong>{t.identifier}</strong></td><td>{bikes.find(b => b.id === t.bike_id)?.identifier || "Unlinked"}</td><td>{t.last_seen_at ? new Date(t.last_seen_at).toLocaleString() : "Never"}</td><td>{t.is_online ? "Online" : "Offline"}</td><td><button className="icon-btn" aria-label={`View ${t.identifier}`}><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div></section>{selected && <div className="detail-backdrop" onClick={() => setSelected(null)}><aside className="detail-drawer tracker-location-drawer" onClick={e => e.stopPropagation()}><div className="detail-heading"><div><span className="eyebrow">LIVE DEVICE LOCATION</span><h2>{selected.identifier}</h2></div><button className="icon-btn" onClick={() => setSelected(null)}><X size={18}/></button></div>{selected.latitude != null && selected.longitude != null ? <><div ref={host} className="tracker-location-map"/><div className="tracker-location-facts"><p><b>Status</b><span className={selected.is_online ? "map-state online" : "map-state offline"}>{selected.is_online ? "Online" : "Offline"}</span></p><p><b>Linked product</b>{product?.identifier || "Unlinked"}</p><p><b>Last seen</b>{selected.last_seen_at ? new Date(selected.last_seen_at).toLocaleString() : "Never"}</p><p><b>Coordinates</b>{Number(selected.latitude).toFixed(6)}, {Number(selected.longitude).toFixed(6)}</p></div><a className="button primary tracker-route" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${selected.latitude}&mlon=${selected.longitude}#map=17/${selected.latitude}/${selected.longitude}`}><MapPin size={15}/> Open live route <ExternalLink size={14}/></a></> : <div className="empty-state"><MapPin size={22}/><strong>No live location yet</strong><span>This device has not sent GPS coordinates. Its location will appear after the next heartbeat.</span></div>}</aside></div>}</>;
}
